![banner](../banner.jpg)

***Training course in data analysis for genomic surveillance of African malaria vectors***

---

# Unrestricted metadata flags

**Theme: Data**

**DISCLAIMER: Please note that the output of the code in the cells below might change over time. This can happen because Python packages and their dependencies change due to updates, or because new data is added.**

This module provides an introduction to metadata flags that have been added recently to the vector resources. These flags are used to filter samples that are "unrestricted", i.e., available for anyone to use freely. What these terms mean will be examined in more details shortly.

This module will not contain a lot of technical code but some functions, such as `sample_metadata` will be used as examples. We will not detail what these functions do in this notebook and we will not be interested in the results of their executions, only on the impact of using the flags on these functions. More details on the use of these functions and their results can be found in the [Introductory course](https://anopheles-genomic-surveillance.github.io/home.html). The use of `sample_metadata` is, for instance, explained in [Workshop 1 Module 2](https://anopheles-genomic-surveillance.github.io/workshop-1/module-2-sample-metadata.html).

## Learning objectives

After completing this module, you will be able to:

* Explain what it means for a sample set to be "unrestricted"
* Understand when to use the `unrestricted_use_only` flags for your analyses
* Use the metadata flags when needed

# Installations and imports

In [2]:
%pip install -q --no-warn-conflicts malariagen_data

In [3]:
import malariagen_data
import os

In [4]:
import plotly.io as pio
pio.renderers.default = "notebook+colab"

In [5]:
try:
    # if running on colab, mount Google Drive
    from google.colab import drive
    drive.mount('drive')
except ImportError:
    pass

In [6]:
results_dir = "drive/MyDrive/Colab Data/ag3-unrestricted-access"
os.makedirs(results_dir, exist_ok=True)

# What is an "unrestricted" sample set and why are some sample sets not "unrestricted"?

Put simply, a sample set is "unrestricted" if anyone can use it however they so choose.

All the sample sets that are accessible using either `Ag3` or `Af1` are open but terms of use apply. These terms of use are available on the [MalariaGEN website](https://www.malariagen.net/mosquito/) and may differ from sample set to sample set. For example, the terms of use for _Anopheles gambiae_ Genomic Surveillance project (which can be found [here](https://www.malariagen.net/data/our-approach-sharing-data/anopheles-gambiae-genomic-surveillance-project-terms-of-use/)) state that there is a "publication embargo \[which\] will expire 24 months after the data is integrated into the Malaria Genome Vector Observatory data repository, or earlier, if the project partner agrees to remove the embargo before the expiry date.".

We created a flag, unrestricted_use, to facilitate checking whether a sample set is out of embargo. It is `True` if the sample set can be used without any restriction and `False` otherwise. Users can access and explore sample sets with a False unrestricted_use flag through the package but they need to be aware that terms of use apply and these differ between sample sets. It is key to respect these terms of use when accessing MalariaGEN resources, this allow us to continue working with the data producers/owners to generate key resources for the community.

## Standard setup used during the entry level course

Let us first look at the standard setup that you will be more familiar with for `Ag3` once you have run the entry level course. We could have used `Af1` in the same way but we assume that users are, at this point, more familiar with `Ag3`.

In [7]:
ag3_default = malariagen_data.Ag3(results_cache=results_dir)

We will start by looking at how many sample sets are "unrestricted".

In [8]:
ag3_default.sample_sets()['unrestricted_use'].value_counts()

unrestricted_use
True     83
False    18
Name: count, dtype: Int64

We see that more than half the sample sets are "unrestricted". We can look at the first few "restricted" sample sets.

In [9]:
ag3_default.sample_sets().query('unrestricted_use == False').head()

/var/tmp/ipykernel_7518/3652335835.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  ag3_default.sample_sets().query('unrestricted_use == False').head()

,sample_set,sample_count,study_id,study_url,terms_of_use_expiry_date,terms_of_use_url,release,unrestricted_use
33,1296-VO-BF-DIABATE-VMF00272,665,1296-VO-BF-DIABATE,https://www.malariagen.net/network/where-we-wo...,2026-09-06,https://malariagen.github.io/vector-data/ag3/a...,3.11,False
34,1351-VO-SS-WEETMAN-VMF00282,90,1351-VO-SS-WEETMAN,https://www.malariagen.net/network/where-we-wo...,2026-09-06,https://malariagen.github.io/vector-data/ag3/a...,3.11,False
35,1338-VO-NG-ADEDAPO-VMF00268,720,1338-VO-NG-ADEDAPO,https://www.malariagen.net/network/where-we-wo...,2026-11-04,https://malariagen.github.io/vector-data/ag3/a...,3.12,False
36,1324-VO-ET-GOLASSA-VMF00257,420,1324-VO-ET-GOLASSA,https://www.malariagen.net/network/where-we-wo...,2026-11-04,https://malariagen.github.io/vector-data/ag3/a...,3.13,False
37,1324-VO-ET-GOLASSA-VMF00275,573,1324-VO-ET-GOLASSA,https://www.malariagen.net/network/where-we-wo...,2027-03-13,https://malariagen.github.io/vector-data/ag3/a...,3.14,False

This cell was run on 20/08/2026. The sample set on the last row that we see is '1324-VO-ET-GOLASSA-VMF00275'. If we look to the `terms_of_use_expiry_date` column, we can see that it is under embargo until 13/03/2027. As it is later than the day this cell was run, it makes sense that is not yet unrestricted. **You may get a very different output depending on when you run this cell.**

## Unrestricted setup

Let us now set up things so that we only access the unrestricted sample sets.

In [10]:
# Construct an Ag3 object using the `unrestricted_use_only` setting.
ag3_unrestricted = malariagen_data.Ag3(unrestricted_use_only=True)

Let us check that only the unrestricted sample sets are part of this resource.

In [11]:
# See the value counts for `unrestricted_use` for all of the sample sets relevant to this object.
ag3_unrestricted.sample_sets()['unrestricted_use'].value_counts()

unrestricted_use
True    83
Name: count, dtype: Int64

We see that all the sample sets are "unrestricted". We can try to look at the first few "restricted" sample sets.

In [12]:
ag3_unrestricted.sample_sets().query('unrestricted_use == False').head()

/var/tmp/ipykernel_7518/2673686400.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  ag3_unrestricted.sample_sets().query('unrestricted_use == False').head()

Empty DataFrame
Columns: [sample_set, sample_count, study_id, study_url, terms_of_use_expiry_date, terms_of_use_url, release, unrestricted_use]
Index: []

We can't find any.

**Well done**

In this module, we have learnt:
    
* Why the use of some data may be restricted
* How to configure the resources to only access the data that is relevant to our scope
* That one might get different results with different configurations. One needs to be careful.

**Congratulations on reaching the end of this notebook.**