## TZ ref admixture - plotting

In [34]:
!pip install -q malariagen_data

In [ ]:
!pip install malariagen_data "xyzservices < 2023.10.1"

Collecting malariagen_data
  Downloading malariagen_data-7.14.0-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 3.1 MB/s eta 0:00:00
Collecting xyzservices<2023.10.1
  Downloading xyzservices-2023.10.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.2/57.2 kB 6.4 MB/s eta 0:00:00
Collecting BioPython (from malariagen_data)
  Downloading biopython-1.81-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 42.8 MB/s eta 0:00:00
Requirement already satisfied: bokeh>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (3.3.0)
Collecting dash (from malariagen_data)
  Downloading dash-2.14.1-py3-none-any.whl (10.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 101.4 MB/s eta 0:00:00
Collecting dash-cytoscape (from malariagen_data)
  Downloading dash_cytoscape-0.3.0-py3-none-any.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 96.6 MB/s eta 0:00:00
Requirement already satisfied: dask[array] in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (2023.8.1)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (2023.6.0)
Requirement already satisfied: gcsfs in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (2023.6.0)
Collecting igv-notebook>=0.2.3 (from malariagen_data)
  Downloading igv_notebook-0.5.2-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.5/302.5 kB 33.3 MB/s eta 0:00:00
Collecting importlib_metadata<5.0 (from malariagen_data)
  Downloading importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Collecting ipinfo!=4.4.1 (from malariagen_data)
  Downloading ipinfo-4.4.3-py3-none-any.whl (24 kB)
Requirement already satisfied: ipyleaflet>=0.17.0 in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (0.17.4)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (7.7.1)
Collecting jupyter-dash (from malariagen_data)
  Downloading jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Requirement already satisfied: llvmlite>0.34 in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (0.41.1)
Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (0.58.1)
Requirement already satisfied: numpy<1.25 in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (1.23.5)
Collecting numpydoc_decorator>=2.1.0 (from malariagen_data)
  Downloading numpydoc_decorator-2.1.0-py3-none-any.whl (11 kB)
Collecting orjson (from malariagen_data)
  Downloading orjson-3.9.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 kB 16.4 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (1.5.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (5.15.0)
Collecting protopunica (from malariagen_data)
  Downloading protopunica-0.14.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 9.0 MB/s eta 0:00:00
Collecting scikit-allel (from malariagen_data)
  Downloading scikit_allel-1.3.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 66.7 MB/s eta 0:00:00
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (1.11.3)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (0.14.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (4.66.1)
Collecting typeguard>=4.0.0 (from malariagen_data)
  Downloading typeguard-4.1.5-py3-none-any.whl (34 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (4.5.0)
Requirement already satisfied: xarray in /usr/local/lib/python3.10/dist-packages (from malariagen_data) (2023.7.0)
Collecting zarr (from malariagen_data)
  Downloading zarr-2.16.1-py3-none-any.whl (206 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.9/206.9 kB 22.2 MB/s eta 0:00:00
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1.0->malariagen_data) (3.1.2)
Requirement already satisfied: contourpy>=1 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1.0->malariagen_data) (1.2.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1.0->malariagen_data) (23.2)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1.0->malariagen_data) (9.4.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1.0->malariagen_data) (6.0.1)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1.0->malariagen_data) (6.3.2)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.10/dist-packages (from igv-notebook>=0.2.3->malariagen_data) (5.5.6)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from igv-notebook>=0.2.3->malariagen_data) (7.34.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from igv-notebook>=0.2.3->malariagen_data) (2.31.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib_metadata<5.0->malariagen_data) (3.17.0)
Requirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from ipinfo!=4.4.1->malariagen_data) (5.3.2)
Requirement already satisfied: aiohttp<=4 in /usr/local/lib/python3.10/dist-packages (from ipinfo!=4.4.1->malariagen_data) (3.8.6)
Requirement already satisfied: traittypes<3,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from ipyleaflet>=0.17.0->malariagen_data) (0.2.1)
Requirement already satisfied: branca>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from ipyleaflet>=0.17.0->malariagen_data) (0.6.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->malariagen_data) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->malariagen_data) (5.7.1)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->malariagen_data) (3.6.6)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->malariagen_data) (3.0.9)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->malariagen_data) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->malariagen_data) (2023.3.post1)
Collecting typing_extensions (from malariagen_data)
  Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from dash->malariagen_data) (2.2.5)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.10/dist-packages (from dash->malariagen_data) (3.0.1)
Collecting dash-html-components==2.0.0 (from dash->malariagen_data)
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-core-components==2.0.0 (from dash->malariagen_data)
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-table==5.0.0 (from dash->malariagen_data)
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting retrying (from dash->malariagen_data)
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Collecting ansi2html (from dash->malariagen_data)
  Downloading ansi2html-1.8.0-py3-none-any.whl (16 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from dash->malariagen_data) (1.5.8)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from dash->malariagen_data) (67.7.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->malariagen_data) (8.2.3)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from dask[array]->malariagen_data) (8.1.7)
Requirement already satisfied: cloudpickle>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from dask[array]->malariagen_data) (2.2.1)
Requirement already satisfied: partd>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from dask[array]->malariagen_data) (1.4.1)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from dask[array]->malariagen_data) (0.12.0)
Requirement already satisfied: decorator>4.1.2 in /usr/local/lib/python3.10/dist-packages (from gcsfs->malariagen_data) (4.4.2)
Requirement already satisfied: google-auth>=1.2 in /usr/local/lib/python3.10/dist-packages (from gcsfs->malariagen_data) (2.17.3)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.10/dist-packages (from gcsfs->malariagen_data) (1.0.0)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.10/dist-packages (from gcsfs->malariagen_data) (2.8.0)
Requirement already satisfied: joblib>=0.9.0b4 in /usr/local/lib/python3.10/dist-packages (from protopunica->malariagen_data) (1.3.2)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.10/dist-packages (from protopunica->malariagen_data) (3.2.1)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from statsmodels->malariagen_data) (0.5.3)
Collecting asciitree (from zarr->malariagen_data)
  Downloading asciitree-0.3.3.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting fasteners (from zarr->malariagen_data)
  Downloading fasteners-0.19-py3-none-any.whl (18 kB)
Collecting numcodecs>=0.10.0 (from zarr->malariagen_data)
  Downloading numcodecs-0.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 43.9 MB/s eta 0:00:00
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<=4->ipinfo!=4.4.1->malariagen_data) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<=4->ipinfo!=4.4.1->malariagen_data) (3.3.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<=4->ipinfo!=4.4.1->malariagen_data) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp<=4->ipinfo!=4.4.1->malariagen_data) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<=4->ipinfo!=4.4.1->malariagen_data) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<=4->ipinfo!=4.4.1->malariagen_data) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<=4->ipinfo!=4.4.1->malariagen_data) (1.3.1)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash->malariagen_data) (2.1.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.2->gcsfs->malariagen_data) (0.3.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.2->gcsfs->malariagen_data) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.2->gcsfs->malariagen_data) (4.9)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel->igv-notebook>=0.2.3->malariagen_data) (6.1.12)
Collecting jedi>=0.16 (from ipython->igv-notebook>=0.2.3->malariagen_data)
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 63.0 MB/s eta 0:00:00
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->igv-notebook>=0.2.3->malariagen_data) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->igv-notebook>=0.2.3->malariagen_data) (3.0.39)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->igv-notebook>=0.2.3->malariagen_data) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->igv-notebook>=0.2.3->malariagen_data) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->igv-notebook>=0.2.3->malariagen_data) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->igv-notebook>=0.2.3->malariagen_data) (4.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.9->bokeh>=3.1.0->malariagen_data) (2.1.3)
Requirement already satisfied: locket in /usr/local/lib/python3.10/dist-packages (from partd>=1.2.0->dask[array]->malariagen_data) (1.0.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (6.5.5)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib->gcsfs->malariagen_data) (1.3.1)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->gcsfs->malariagen_data) (2.11.1)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->gcsfs->malariagen_data) (2.3.3)
Requirement already satisfied: google-resumable-media>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->gcsfs->malariagen_data) (2.6.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->igv-notebook>=0.2.3->malariagen_data) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->igv-notebook>=0.2.3->malariagen_data) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->igv-notebook>=0.2.3->malariagen_data) (2023.7.22)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->gcsfs->malariagen_data) (1.61.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->gcsfs->malariagen_data) (3.20.3)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media>=2.3.2->google-cloud-storage->gcsfs->malariagen_data) (1.5.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->igv-notebook>=0.2.3->malariagen_data) (0.8.3)
Requirement already satisfied: pyzmq<25,>=17 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (23.2.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (23.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (5.5.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (5.9.2)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (6.5.4)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (0.17.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (0.18.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (1.0.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->igv-notebook>=0.2.3->malariagen_data) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->igv-notebook>=0.2.3->malariagen_data) (0.2.9)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs->malariagen_data) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs->malariagen_data) (3.2.2)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.6.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (3.11.0)
Requirement already satisfied: jupyter-server>=1.8 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (1.24.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (0.2.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (4.9.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (4.11.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (6.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (0.4)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->malariagen_data) (0.2.2)

In [35]:
import malariagen_data
import dask.array as da
import allel
import numpy as np
import plotly.express as px
import pandas as pd
from dask.diagnostics import ProgressBar
import google.colab
import os

In [ ]:
google.colab.drive.mount("drive")

Mounted at drive

In [ ]:
results_dir = "drive/MyDrive/Tanzania/TZ-ref-admixture-131123"

In [36]:
ag3 = malariagen_data.Ag3()

In [ ]:
def get_plink_file_path(
    contig,
    n_snps,
    min_minor_ac,
    thin_offset,
    max_missing_an,
):
    return f"{results_dir}/{contig}.{n_snps}.{min_minor_ac}.{thin_offset}.{max_missing_an}"

In [ ]:
#set seed

In [ ]:
def load_admixture(
    contig,
    n_snps,
    thin_offset,
    min_minor_ac,
    K,
    seed=42,
):
    contig_label = contig.replace(",", ".")
    contig_label = f"chr{contig_label}"
    plink_file_path = get_plink_file_path(
        contig=contig_label, n_snps=n_snps, min_minor_ac=min_minor_ac, thin_offset=thin_offset, max_missing_an=0
    )

    fam_file_path = f"{plink_file_path}.fam"
    admixture_dir = f"{plink_file_path}.admixture/{seed}"
    Q_file_path = f"{admixture_dir}/{K}.Q"
    P_file_path = f"{admixture_dir}/{K}.P"
    log_file_path = f"{admixture_dir}/{K}.log"

    # load results - sample IDs
    df_fam = pd.read_csv(
        fam_file_path,
        sep=" ",
        header=None,
        names=["family_id", "sample_id", "father", "mother", "sex", "phenotype"],
        index_col=False,
    )
    samples = df_fam["sample_id"]
    df_samples = ag3.sample_metadata()
    df_samples = (
        df_samples
        .set_index("sample_id")
        .loc[samples]
    )

    # load results - ancestry fractions
    df_q = pd.read_csv(
        Q_file_path,
        sep=" ",
        header=None,
        names=[f"pop{i}" for i in range(K)],
        index_col=False,
    )
    df_q["popmax"] = df_q.idxmax(axis="columns")
    df_q["popmax_frac"] = df_q.apply(lambda row: row[row["popmax"]], axis="columns")
    df_q.set_index(samples, inplace=True)

    df_out = df_q.join(df_samples).reset_index()
    df_out.attrs["K"] = K
    return df_out

In [ ]:
df = load_admixture(
    contig="3L:15,000,000-41,000,000",
    n_snps=50_000,
    thin_offset=0,
    min_minor_ac=5,
    K=2,
)
df.head()

,sample_id,pop0,pop1,popmax,popmax_frac,partner_sample_id,contributor,country,location,year,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,AB0085-Cx,0.999990,0.000010,pop0,0.999990,BF2-4,Austin Burt,Burkina Faso,Pala,2012,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2012,BF-09_gamb_2012_07,BF-09_gamb_2012_Q3,BF-09_Houet_gamb_2012,BF-09_Houet_gamb_2012_07,BF-09_Houet_gamb_2012_Q3
1,AB0086-Cx,0.994438,0.005562,pop0,0.994438,BF2-6,Austin Burt,Burkina Faso,Pala,2012,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2012,BF-09_gamb_2012_07,BF-09_gamb_2012_Q3,BF-09_Houet_gamb_2012,BF-09_Houet_gamb_2012_07,BF-09_Houet_gamb_2012_Q3
2,AB0087-C,0.999990,0.000010,pop0,0.999990,BF3-3,Austin Burt,Burkina Faso,Bana Village,2012,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2012,BF-09_colu_2012_07,BF-09_colu_2012_Q3,BF-09_Houet_colu_2012,BF-09_Houet_colu_2012_07,BF-09_Houet_colu_2012_Q3
3,AB0088-C,0.999990,0.000010,pop0,0.999990,BF3-5,Austin Burt,Burkina Faso,Bana Village,2012,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2012,BF-09_colu_2012_07,BF-09_colu_2012_Q3,BF-09_Houet_colu_2012,BF-09_Houet_colu_2012_07,BF-09_Houet_colu_2012_Q3
4,AB0089-Cx,0.999990,0.000010,pop0,0.999990,BF3-8,Austin Burt,Burkina Faso,Bana Village,2012,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2012,BF-09_colu_2012_07,BF-09_colu_2012_Q3,BF-09_Houet_colu_2012,BF-09_Houet_colu_2012_07,BF-09_Houet_colu_2012_Q3

In [ ]:
df['cohort_admin1_year'].unique()

array(['BF-09_gamb_2012', 'BF-09_colu_2012', 'BF-09_colu_2014',
       'BF-09_gamb_2014', 'BF-07_gamb_2004', 'KE-14_arab_2012',
       'KE-14_gcx3_2012', 'KE-14_gamb_2000', 'KE-14_arab_2007',
       'TZ-05_gcx3_2015', 'TZ-05_arab_2015', 'TZ-05_gamb_2015',
       'TZ-26_arab_2012', 'TZ-13_arab_2012', 'TZ-25_gamb_2013',
       'TZ-25_gcx3_2013', 'TZ-25_arab_2013', 'UG-E_arab_2012',
       'UG-E_gamb_2012', 'UG-W_gamb_2012', 'UG-W_arab_2012'], dtype=object)

In [ ]:
import plotly.graph_objects as go
import plotly.subplots
import plotly.express as px

In [ ]:
# plotly.subplots.make_subplots?

In [ ]:
def plot_admixture(
    contig,
    n_snps,
    thin_offset,
    min_minor_ac,
    by = 'cohort_admin1_year',
    col_keys = None,
    k_vals=list(range(2, 7)),
    colors=px.colors.qualitative.Plotly,
    width=900,
    height=900,
):

    # setup
    #read fam file for sample ids
    contig_label = contig.replace(",", ".")
    contig_label = f"chr{contig_label}"
    plink_file_path = get_plink_file_path(contig=contig_label, n_snps=n_snps, thin_offset=0, min_minor_ac=min_minor_ac, max_missing_an=0)
    fam_file_path = f"{plink_file_path}.fam"
    df_fam = pd.read_csv(
            fam_file_path,
            sep=" ",
            header=None,
            names=["family_id", "sample_id", "father", "mother", "sex", "phenotype"],
            index_col=False,
        )
    samples = df_fam["sample_id"]
    samples = samples.tolist()


    df_samples = ag3.sample_metadata(sample_query=f'sample_id in {samples}')

    #allow change of order. This could probably be coded better.
    if col_keys is not None:
      col_keys = col_keys
    else:
      col_keys = df_samples[by].unique().tolist()

    rows = len(k_vals)
    cols = len(col_keys)
    col_widths = df_samples[by].value_counts().loc[col_keys].to_list()

    # create figure
    fig = plotly.subplots.make_subplots(
        rows=rows,
        cols=cols,
        shared_yaxes=True,
        column_titles=col_keys,
        row_titles=[f"K={K}" for K in k_vals],
        column_widths=col_widths,
        x_title="Samples",
        y_title=f"Ancestry fraction",
        horizontal_spacing=.01,
        vertical_spacing=.02,
    )

    for i, K in enumerate(k_vals):

        df = load_admixture(
            contig=contig,
            n_snps=n_snps,
            thin_offset=thin_offset,
            min_minor_ac=min_minor_ac,
            K=K,
        )
        data_frame = df.sort_values(by=["popmax", "popmax_frac"], ascending=False)
        K = data_frame.attrs["K"]
        admx_cols = [f"pop{i}" for i in range(K)]
        g = data_frame.groupby(by=by)

        for j, key in enumerate(col_keys):
            jx = g.groups[key]
            dfk = data_frame.loc[jx]
            x = "sample_id"
            for y, color in zip(admx_cols, colors):
                fig.add_trace(
                    go.Bar(
                        x=dfk["sample_id"],
                        y=dfk[y],
                        marker_color=color,
                        name=y,
                    ),
                    row=i+1, col=j+1,
                )

    fig.update_yaxes(
        range=(0, 1)
    )

    fig.update_xaxes(
        tickmode='array',
        tickvals=[],
    )

    fig.update_yaxes(
        tickmode='array',
        tickvals=[],
    )

    fig.update_layout(
        barmode="stack",
        bargap=0,
        width=width,
        height=height,
        showlegend=False,
        title_text=None,
    )

    fig.update_traces(
        marker=dict(line=dict(width=0)),
    )

    # rotate all the subtitles using len of cohorts
    for annotation in fig['layout']['annotations'][0:cols]:
        annotation['textangle']=-25
        annotation['xanchor'] = 'left'




    return fig

In [37]:
df_samples = ag3.sample_metadata(sample_query = 'taxon in ["gambiae","coluzzii"] and country == "Burkina Faso" or taxon in ["gambiae","coluzzii","arabiensis","gcx3"] and country == "Uganda" or country == "Tanzania" or country == "Kenya"')

In [38]:
df_samples.groupby(['country','taxon','cohort_admin1_year','location']).size()

country       taxon       cohort_admin1_year  location
Burkina Faso  coluzzii    BF-09_colu_2012     Bana Village       42
                                              Pala               11
                                              Souroukoudinga     29
                          BF-09_colu_2014     Bana Village       47
                                              Souroukoudinga      6
              gambiae     BF-07_gamb_2004     Monomtenga         13
                          BF-09_gamb_2012     Bana Village       23
                                              Pala               48
                                              Souroukoudinga     28
                          BF-09_gamb_2014     Bana Village       15
                                              Pala               16
                                              Souroukoudinga     15
Kenya         arabiensis  KE-14_arab_2007     Kilifi              3
                          KE-14_arab_2012     Kilifi             10
              gambiae     KE-14_gamb_2000     Kilifi             19
              gcx3        KE-14_gcx3_2012     Kilifi             54
Tanzania      arabiensis  TZ-05_arab_2015     Muleba            137
                          TZ-13_arab_2012     Tarime             47
                          TZ-25_arab_2013     Muheza              1
                          TZ-26_arab_2012     Moshi              40
              gambiae     TZ-05_gamb_2015     Muleba             32
                          TZ-25_gamb_2013     Muheza             32
              gcx3        TZ-05_gcx3_2015     Muleba              1
                          TZ-25_gcx3_2013     Muheza             10
Uganda        arabiensis  UG-E_arab_2012      Nagongera          81
                          UG-W_arab_2012      Kihihi              1
              gambiae     UG-E_gamb_2012      Nagongera         112
                          UG-W_gamb_2012      Kihihi             95
dtype: int64

In [ ]:
df_tz_samples = ag3.sample_metadata(sample_query = 'country == "Tanzania"')

In [ ]:
df_tz_samples.groupby(['country','taxon','cohort_admin1_year','location']).size()

country   taxon       cohort_admin1_year  location
Tanzania  arabiensis  TZ-05_arab_2015     Muleba      137
                      TZ-13_arab_2012     Tarime       47
                      TZ-25_arab_2013     Muheza        1
                      TZ-26_arab_2012     Moshi        40
          gambiae     TZ-05_gamb_2015     Muleba       32
                      TZ-25_gamb_2013     Muheza       32
          gcx3        TZ-05_gcx3_2015     Muleba        1
                      TZ-25_gcx3_2013     Muheza       10
dtype: int64

In [ ]:
#Muheza similar to Kenya
fig = plot_admixture(
    contig="3L:15,000,000-41,000,000",
    n_snps=50_000,
    thin_offset=0,
    min_minor_ac=5,
    by='cohort_admin1_year',
    col_keys=['UG-E_arab_2012','KE-14_arab_2007','UG-W_arab_2012','KE-14_arab_2012','TZ-13_arab_2012','TZ-26_arab_2012','TZ-25_arab_2013','TZ-05_arab_2015',
              'BF-09_colu_2012', 'BF-09_colu_2014',
              'BF-09_gamb_2012','BF-09_gamb_2014', 'BF-07_gamb_2004','UG-E_gamb_2012','UG-W_gamb_2012','KE-14_gamb_2000','TZ-25_gamb_2013','TZ-05_gamb_2015',
              'KE-14_gcx3_2012', 'TZ-25_gcx3_2013','TZ-05_gcx3_2015',
              ],
    )
fig

In [ ]:
fig = plot_admixture(
    contig="3L:15,000,000-41,000,000",
    n_snps=50_000,
    thin_offset=0,
    min_minor_ac=5,
    by='taxon',
    col_keys=['arabiensis',
              'coluzzii',
              'gambiae',
              'gcx3'],
)
fig

In [ ]:
contig="3L:15,000,000-41,000,000"
contig_label = contig.replace(",", ".")
contig_label = f"chr{contig_label}"
get_plink_file_path(
    contig=contig_label,
    n_snps=50_000,
    thin_offset=0,
    min_minor_ac=5,
    max_missing_an=0,
)

'drive/MyDrive/Tanzania/TZ-ref-admixture-131123/chr3L:15.000.000-41.000.000.50000.5.0.0'

In [ ]:
!grep CV drive/MyDrive/Tanzania/TZ-ref-admixture-131123/chr3L:15.000.000-41.000.000.50000.5.0.0.admixture/42/*.log

drive/MyDrive/Tanzania/TZ-ref-admixture-131123/chr3L:15.000.000-41.000.000.50000.5.0.0.admixture/42/2.log:CV error (K=2): 0.11539
drive/MyDrive/Tanzania/TZ-ref-admixture-131123/chr3L:15.000.000-41.000.000.50000.5.0.0.admixture/42/3.log:CV error (K=3): 0.10991
drive/MyDrive/Tanzania/TZ-ref-admixture-131123/chr3L:15.000.000-41.000.000.50000.5.0.0.admixture/42/4.log:CV error (K=4): 0.10800
drive/MyDrive/Tanzania/TZ-ref-admixture-131123/chr3L:15.000.000-41.000.000.50000.5.0.0.admixture/42/5.log:CV error (K=5): 0.10634
drive/MyDrive/Tanzania/TZ-ref-admixture-131123/chr3L:15.000.000-41.000.000.50000.5.0.0.admixture/42/6.log:CV error (K=6): 0.10684

In [ ]:
def extract_cv_error(
    contig,
    n_snps,
    thin_offset,
    min_minor_ac,
    k_vals=list(range(2, 7)),
    seed=42,
):
    contig_label = contig.replace(",", ".")
    contig_label = f"chr{contig_label}"
    plink_file_path = get_plink_file_path(
        contig=contig_label,
        n_snps=n_snps,
        thin_offset=thin_offset,
        min_minor_ac=min_minor_ac,
        max_missing_an=0,
    )
    admixture_path = f"{plink_file_path}.admixture/{seed}"
    cv_error = []
    for k in k_vals:
        log_path = f"{admixture_path}/{k}.log"
        with open(log_path, mode="rt") as log_file:
            for line in log_file.readlines():
                if line.startswith("CV error"):
                    e = float(line.split(":")[1])
                    cv_error.append(e)
    return pd.DataFrame({"contig": contig, "seed": seed, "k": k_vals, "cv_error": cv_error})

In [ ]:
df_cv_error = extract_cv_error(
                              contig="3L:15,000,000-41,000,000",
                              n_snps=50_000,
                              thin_offset=0,
                              min_minor_ac=5,
                              )

In [ ]:
fig = px.line(
    data_frame=df_cv_error,
    x="k",
    y="cv_error",
    line_group="contig",
    color="contig",
    markers=True,
    labels={
        'k': 'K',
        'cv_error': "Cross-validation error",
        "contig": "Contig",
    },
    width=600,
    height=400,
)

fig.update_xaxes(
    tickmode='array',
    tickvals=[2, 3, 4, 5, 6],
)

In [ ]:
fig = px.scatter(
    data_frame=df_cv_error_reps,
    x="k",
    y="cv_error",
    color="contig",
    labels={
        'k': 'K',
        'cv_error': "Cross-validation error",
        "contig": "Contig",
    },
    width=600,
    height=400,
)

fig.update_xaxes(
    tickmode='array',
    tickvals=[2, 3, 4, 5, 6],
)

In [ ]:
fig = px.violin(
    data_frame=df_cv_error_reps,
    x="k",
    y="cv_error",
    # color="contig",
    points="all",
    labels={
        'k': 'K',
        'cv_error': "Cross-validation error",
        "contig": "Contig",
    },
    width=600,
    height=400,
)

fig.update_xaxes(
    tickmode='array',
    tickvals=[2, 3, 4, 5, 6],
)

fig.update_traces(
    pointpos=0,
)

In [ ]:
#combine multiple runs with pong.

In [ ]:
!pip install pong

Requirement already satisfied: pong in /usr/local/lib/python3.10/dist-packages (1.5)
Requirement already satisfied: numpy~=1.19 in /usr/local/lib/python3.10/dist-packages (from pong) (1.23.5)
Requirement already satisfied: tornado~=6.1 in /usr/local/lib/python3.10/dist-packages (from pong) (6.3.2)
Requirement already satisfied: munkres~=1.1 in /usr/local/lib/python3.10/dist-packages (from pong) (1.1.4)
Requirement already satisfied: networkx~=2.5 in /usr/local/lib/python3.10/dist-packages (from pong) (2.8.8)

In [ ]:
!pong -h

usage: pong [-h] -m FILEMAP [-c IGNORE_COLS] [-o OUTPUT_DIR] [-i IND2POP] [-n POP_NAMES]
            [-l COLOR_LIST] [-f] [-s SIM_THRESHOLD] [--col_delim COL_DELIM]
            [--dist_metric DIST_METRIC] [--disable_server] [-p PORT] [-v] [-g]

-------------------------------- pong, v1.5 --------------------------------

options:
  -h, --help            show this help message and exit
  -m FILEMAP, --filemap FILEMAP
                        path to params file containing information about input Q-matrix files
  -c IGNORE_COLS, --ignore_cols IGNORE_COLS
                        ignore the first i columns of every data line. Typically 5 for Structure
                        output and 0 for ADMIXTURE output. Default = 0
  -o OUTPUT_DIR, --output_dir OUTPUT_DIR
                        specify output dir for files to be written to. By default, pong makes a
                        folder named "pong_output_datetime" in the current working directory,
                        where "datetime" is the current system date and time.
  -i IND2POP, --ind2pop IND2POP
                        ind2pop data (can be either a Q-matrix column number or the path to a file
                        containing the data).
  -n POP_NAMES, --pop_names POP_NAMES
                        Path to file containing population order/names.
  -l COLOR_LIST, --color_list COLOR_LIST
                        List of colors to be used for visualization. If this file is not included,
                        then default colors will be used for visualization.
  -f, --force           force overwrite already existing output directory. By default, pong will
                        prompt the user before overwriting.
  -s SIM_THRESHOLD, --sim_threshold SIM_THRESHOLD
                        choose threshold to combine redundant clusters at a given K. Default =
                        0.97
  --col_delim COL_DELIM
                        Provide the character on which to split columns. Default is whitespace (of
                        any length).
  --dist_metric DIST_METRIC
                        distance metric to be used for comparing cluster similarities. Choose from
                        ['sum_squared', 'percent', 'G', 'jaccard']. Default = jaccard
  --disable_server      run pong's algorithm without initializing a server instance or visualizing
                        results.
  -p PORT, --port PORT  Specify port on which the server should locally host. Default = 4000.
  -v, --verbose         Report more details about clustering results to the command line, and
                        print all cluster distances in the output files (by default, only the best
                        5 are printed).
  -g, --greedy          Force the use of the greedy algorithm if a set of disjoint cliques cannot
                        be found. By default, pong prompts the user with a choice of whether to
                        continue with the greedy algorithm, or to exit and re-run with different
                        parameters.

In [ ]:
df_samples=df_samples.reset_index()

In [ ]:
#setup pong

In [ ]:
contig="3L:15,000,000-41,000,000"
contig_label = contig.replace(",", ".")
contig_label = f"chr{contig_label}"
plink_file_path = get_plink_file_path(
    contig=contig_label,
    n_snps=50_000,
    thin_offset=0,
    min_minor_ac=5,
    max_missing_an=0,
)

In [ ]:
plink_file_path

'drive/MyDrive/Tanzania/TZ-admixture-021123/chr3L:15.000.000-41.000.000.5000.5.0.0'

In [ ]:
#get mapfile
cola = []
colb = []
for seed in range(0,2):
  for k in range(2,8):
    cola.append(f'{seed}_{k}')
    colb.append(f'{plink_file_path}.admixture/{seed}/{k}.Q')

In [ ]:
#get mapfile
cola = []
colb = []
for k in range(2,8):
  cola.append(f'{seed}_{k}')
  colb.append(f'{plink_file_path}.admixture/1/{k}.Q')

In [ ]:
mapfile = pd.DataFrame({'a': cola, 'b': colb})

In [ ]:
mapfile_txt = mapfile.to_csv(f'{plink_file_path}.admixture/mapfile.txt',sep='\t',index=False, header=False)

In [ ]:
ind2pop=df_samples['cohort_admin1_year']

In [ ]:
ind2pop_txt = ind2pop.to_csv(f'{plink_file_path}.admixture/ind2pop.txt',sep='\t',index=False, header=False)

In [ ]:
#get pop order
pop_order=ind2pop.unique()

In [ ]:
poporder = pd.DataFrame({'a': pop_order})

In [ ]:
poporder

                 a
0  TZ-13_arab_2012
1  TZ-05_arab_2015
2  TZ-26_arab_2012
3  KE-14_arab_2012
4  KE-14_gamb_2000
5  TZ-25_gamb_2013
6  TZ-05_gamb_2015
7  KE-14_gcx3_2012
8  TZ-25_gcx3_2013

In [ ]:
poporder_txt = poporder.to_csv(f'{plink_file_path}.admixture/poporder.txt',sep='\t',index=False, header=False)

In [ ]:
!pong -m {plink_file_path}.admixture/mapfile.txt -i {plink_file_path}.admixture/ind2pop.txt -n {plink_file_path}.admixture/poporder.txt -o {plink_file_path}/pong

Output dir pong already exists.
Overwrite? (y/n): y

-------------------------------------------------------------------
                            p o n g
      by A. Behr, K. Liu, T. Devlin, G. Liu-Fang, and S. Ramachandran
                       Version 1.5 (2021)
-------------------------------------------------------------------
-------------------------------------------------------------------

Parsing input and generating cluster network graph
Traceback (most recent call last):
  File "/usr/local/bin/pong", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pong/main.py", line 295, in main
    run_pong(*run_pong_args)
  File "/usr/local/lib/python3.10/dist-packages/pong/main.py", line 323, in run_pong
    parse.parse_multicluster_input(pongdata, pong_filemap, opts.ignore_cols,
  File "/usr/local/lib/python3.10/dist-packages/pong/parse.py", line 30, in parse_multicluster_input
    qfiles_info = np.genfromtxt(filemap, delimiter='\t',
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 2187, in genfromtxt
    testing_value = first_values[j]
IndexError: list index out of range

In [ ]:
df_cv_error

      contig  seed  k  cv_error
0   KB663610    42  2   0.19747
1   KB663610    42  3   0.19911
2   KB663610    42  4   0.20564
3   KB663610    42  5   0.21316
4   KB663610    42  6   0.22093
5   KB663721    42  2   0.19633
6   KB663721    42  3   0.20255
7   KB663721    42  4   0.20453
8   KB663721    42  5   0.21180
9   KB663721    42  6   0.21928
10  KB663832    42  2   0.20910
11  KB663832    42  3   0.20954
12  KB663832    42  4   0.21491
13  KB663832    42  5   0.21980
14  KB663832    42  6   0.22608
15  KB663943    42  2   0.20335
16  KB663943    42  3   0.20920
17  KB663943    42  4   0.21093
18  KB663943    42  5   0.21748
19  KB663943    42  6   0.22514
20  KB664054    42  2   0.19547
21  KB664054    42  3   0.20084
22  KB664054    42  4   0.20413
23  KB664054    42  5   0.21039
24  KB664054    42  6   0.21785
25  KB664165    42  2   0.19048
26  KB664165    42  3   0.19314
27  KB664165    42  4   0.20006
28  KB664165    42  5   0.20731
29  KB664165    42  6   0.21526
30  KB664255    42  2   0.18733
31  KB664255    42  3   0.19438
32  KB664255    42  4   0.19779
33  KB664255    42  5   0.20469
34  KB664255    42  6   0.21255
35  KB664266    42  2   0.19597
36  KB664266    42  3   0.19742
37  KB664266    42  4   0.20339
38  KB664266    42  5   0.20765
39  KB664266    42  6   0.21499
40  KB664277    42  2   0.23471
41  KB664277    42  3   0.22946
42  KB664277    42  4   0.22951
43  KB664277    42  5   0.23106
44  KB664277    42  6   0.23302
45  KB663633    42  2   0.20730
46  KB663633    42  3   0.21025
47  KB663633    42  4   0.21107
48  KB663633    42  5   0.21457
49  KB663633    42  6   0.22039

In [ ]:
df_cv_error.iloc[df_cv_error.groupby("contig")["cv_error"].idxmin()]

      contig  seed  k  cv_error
0   KB663610    42  2   0.19747
45  KB663633    42  2   0.20730
5   KB663721    42  2   0.19633
10  KB663832    42  2   0.20910
15  KB663943    42  2   0.20335
20  KB664054    42  2   0.19547
25  KB664165    42  2   0.19048
30  KB664255    42  2   0.18733
35  KB664266    42  2   0.19597
41  KB664277    42  3   0.22946

In [ ]:
df_cv_error_reps.iloc[df_cv_error_reps.groupby(["contig", "seed"])["cv_error"].idxmin()]

      contig   seed  k  cv_error
0   KB663610     42  2   0.19747
5   KB663610  64000  2   0.19731
90  KB663633     42  2   0.20730
95  KB663633  64000  2   0.20720
10  KB663721     42  2   0.19633
15  KB663721  64000  2   0.19630
20  KB663832     42  2   0.20910
25  KB663832  64000  2   0.20915
30  KB663943     42  2   0.20335
35  KB663943  64000  2   0.20339
40  KB664054     42  2   0.19547
45  KB664054  64000  2   0.19535
50  KB664165     42  2   0.19048
55  KB664165  64000  2   0.19067
60  KB664255     42  2   0.18733
65  KB664255  64000  2   0.18728
70  KB664266     42  2   0.19597
75  KB664266  64000  2   0.19607
81  KB664277     42  3   0.22946
86  KB664277  64000  3   0.22939